# Generated by Django 5.2.4 on 2025-08-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_task_scheduled_date_alter_subtask_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='description',
        ),
    ]
