# Generated by Django 5.2.4 on 2025-08-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_remove_subtask_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaggedItme",
            new_name="TaggedItem",
        ),
    ]
