# Generated by Django 5.2.4 on 2025-08-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_alter_taggeditem_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggeditem",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_items",
                to="scheduler.task",
            ),
        ),
    ]
