# Generated by Django 5.2.5 on 2025-08-16 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_task_scheduler_t_user_id_dc5433_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'user')},
        ),
    ]
