# Generated by Django 5.2.5 on 2025-08-19 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0008_alter_tag_title_alter_tag_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taskcategory",
            unique_together={("title", "user")},
        ),
    ]
