# Generated by Django 5.2.5 on 2025-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0010_alter_task_dead_line_alter_task_scheduled_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["scheduled_date"]},
        ),
    ]
