# Generated by Django 5.2.5 on 2025-10-29 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0013_alter_task_dead_line_alter_task_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="scheduled_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
